services:
  mysql:
    image: mysql:8.0
    container_name: doctor_appointment_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: doctorappointementsystem
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: